/**
 * @file namespace.hpp
 *
 * @author Oliver Arafat
 *
 * @brief The namespace ::ltl2fsm
 *
 * @note DOCUMENTED -- NO TEST
 */

#ifndef LTL2FSM__BASE__NAMESPACE__HPP
#define LTL2FSM__BASE__NAMESPACE__HPP

#include <ltl2fsm/base/generic_namespace_macros.hpp>


#define LTL2FSM__BEGIN__NAMESPACE__LTL2FSM LTL2FSM__BASE__GENERIC_BEGIN_NAMESPACE(ltl2fsm)
#define LTL2FSM__END__NAMESPACE__LTL2FSM   LTL2FSM__BASE__GENERIC_END_NAMESPACE(ltl2fsm)

#define LTL2FSM__BEGIN__NAMESPACE__INTERNAL LTL2FSM__BASE__GENERIC_BEGIN_NAMESPACE(internal)
#define LTL2FSM__END__NAMESPACE__INTERNAL LTL2FSM__BASE__GENERIC_END_NAMESPACE(internal)


LTL2FSM__BEGIN__NAMESPACE__LTL2FSM;
LTL2FSM__END__NAMESPACE__LTL2FSM;

LTL2FSM__BEGIN__NAMESPACE__INTERNAL;
LTL2FSM__END__NAMESPACE__INTERNAL;


#endif
